import fs from 'fs';
import { OpenAIApi, Configuration } from 'openai';
import { QueryData, AzureOpenAIResponse } from './interfaces';
import fetch from 'cross-fetch';
import './config';

const OPENAI_API_KEY = process.env.OPENAI_API_KEY;
const OPENAI_ENDPOINT = process.env.OPENAI_ENDPOINT;
const OPENAI_MODEL = process.env.OPENAI_MODEL;
const OPENAI_API_VERSION = process.env.OPENAI_API_VERSION;

async function getAzureOpenAICompletion(prompt: string, temperature = 0) : Promise<string> {

    if (!OPENAI_API_KEY || !OPENAI_ENDPOINT || !OPENAI_MODEL) {
        throw new Error('Missing Azure OpenAI API key, endpoint, or model in environment variables.');
    }

    // While it's possible to use the OpenAI SDK (as of today) with a little work, we'll use the REST API directly for Azure OpenAI calls.
    // https://learn.microsoft.com/en-us/azure/cognitive-services/openai/reference
    const url = `${OPENAI_ENDPOINT}/openai/deployments/${OPENAI_MODEL}/chat/completions?api-version=${OPENAI_API_VERSION}`;
    const data = {
        max_tokens: 1024,
        temperature,
        messages: [{ role: 'user', content: prompt }]
    };

    try {
        const response = await fetch(url, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'api-key': `${OPENAI_API_KEY}`,
            },
            body: JSON.stringify(data),
        });

        const completion = await response.json() as AzureOpenAIResponse;
        let content = '';
        if (completion.choices.length) {
            content = completion.choices[0].message?.content.trim();
            console.log('Output:', content);
        }
        return content;
    }
    catch (e) {
        console.error('Error getting data:', e);
        throw e;
    }
}

async function getOpenAICompletion(prompt: string, temperature = 0) : Promise<string> {

    if (!OPENAI_API_KEY) {
        throw new Error('Missing OpenAI API key in environment variables.');
    }

    const configuration = new Configuration({ apiKey: OPENAI_API_KEY });

    try {
        const openai = new OpenAIApi(configuration);
        const completion = await openai.createChatCompletion({
            model: 'gpt-3.5-turbo', // gpt-3.5-turbo, gpt-4
            max_tokens: 1024,
            temperature,
            messages: [{ role: 'user', content: prompt }]
        });

        let content = '';
        if (completion.data.choices.length) {
            content = completion.data.choices[0].message?.content.trim() as string;
            console.log('Output:', content);
        }
        return content;
    }
    catch (e) {
        console.error('Error getting data:', e);
        throw e;
    }
}

function callOpenAI(prompt: string, temperature = 0) {
    const isAzureOpenAI = OPENAI_API_KEY && OPENAI_ENDPOINT && OPENAI_MODEL;
    if (isAzureOpenAI) {
        return getAzureOpenAICompletion(prompt, temperature);
    }
    else {
        return getOpenAICompletion(prompt, temperature);
    }
}

async function getSQL(userPrompt: string): Promise<QueryData> {
    // Get the high-level database schema summary to be used in the prompt.
    // The db.schema file could be generated by a background process or the 
    // schema could be dynamically retrieved.
    const dbSchema = await fs.promises.readFile('db.schema', 'utf8');

    const prompt = `
    PostgreSQL tables, with their properties:

    ${dbSchema}

    User prompt: ${userPrompt}

    Rules:
    - Convert any strings to a PostgreSQL parameterized query value to avoid SQL injection attacks.
    
    Return a JSON object with the SQL query and the parameter values in it. 
    
    Example: { "sql": "", "paramValues": [] }
    `;

    let queryData: QueryData = { sql: '', paramValues: [] };
    try {
        const results = await callOpenAI(prompt);
        if (results) {
            queryData = JSON.parse(results);
            if (isProhibitedQuery(queryData.sql)) {
                queryData.sql = '';
            }
        }
    }
    catch (e) {
        console.log(e);
    }

    return queryData;
}

function isProhibitedQuery(query: string): boolean {
    const prohibitedKeywords = [
        'insert', 'update', 'delete', 'drop', 'truncate', 'alter', 'create', 'replace',
        'information_schema', 'pg_catalog', 'pg_tables', 'pg_namespace', 'pg_class',
        'table_schema', 'table_name', 'column_name', 'column_default', 'is_nullable',
        'data_type', 'udt_name', 'character_maximum_length', 'numeric_precision',
        'numeric_scale', 'datetime_precision', 'interval_type', 'collation_name',
        'grant', 'revoke', 'rollback', 'commit', 'savepoint', 'vacuum', 'analyze'
    ];
    const queryLower = query.toLowerCase();
    return prohibitedKeywords.some(keyword => queryLower.includes(keyword));
}

async function completeEmailSMSMessages(userPrompt: string, company: string, contactName: string) {
    console.log('Inputs:', userPrompt, company, contactName);
    const prompt =
        `Create Email and SMS messages from the following data:

    User Prompt: ${userPrompt}
    Contact Name: ${contactName}

    Rules:
    - Generate a subject line for the email message.
    - Use the User Prompt to generate the messages. 
    - All messages should have a friendly tone. 
    - SMS messages should be in plain text format and no more than 160 characters. 
    - Start the message with "Hi <Contact Name>,\n\n". 
    - Add carriage returns to the email message to make it easier to read. 
    - End with a signature line that says "Sincerely,\nCustomer Service".
    - Return a JSON object with the emailSubject, emailBody, and SMS message values in it. 

    Example JSON object: { "emailSubject": "", "emailBody": "", "sms": "" }
    `;

    const content =  await callOpenAI(prompt, 0.5);
    return content;
}

export { completeEmailSMSMessages, getSQL };